//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreadingHW.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThreadingHW.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 78
        ///2
        ///63
        ///22
        ///41
        ///87
        ///73
        ///41
        ///86
        ///58
        ///87
        ///14
        ///20
        ///24
        ///27
        ///68
        ///17
        ///34
        ///48
        ///23
        ///85
        ///40
        ///38
        ///94
        ///87
        ///51
        ///44
        ///26
        ///78
        ///78
        ///33
        ///83
        ///60
        ///49
        ///74
        ///43
        ///62
        ///42
        ///81
        ///90
        ///12
        ///33
        ///90
        ///51
        ///99
        ///51
        ///71
        ///70
        ///24
        ///84
        ///49
        ///77
        ///81
        ///14
        ///74
        ///35
        ///52
        ///19
        ///8
        ///68
        ///29
        ///68
        ///63
        ///21
        ///51
        ///18
        ///48
        ///91
        ///65
        ///67
        ///94
        ///93
        ///38
        ///30
        ///98
        ///55
        ///29
        ///74
        ///18
        ///6
        ///96
        ///11
        ///66
        ///12
        ///14
        ///64
        ///34
        ///96
        ///52
        ///65
        ///19
        ///45
        ///73
        ///22
        ///85
        ///83
        ///26
        ///94
        ///58
        ///83
        ///89
        ///7
        ///90
        ///30
        ///79
        ///97
        ///25
        ///26
        ///83
        ///95
        ///77
        ///64
        ///28
        ///21
        ///24
        ///49
        ///18
        ///99
        ///97
        ///86
        ///34
        ///83
        ///27
        ///30
        ///95
        ///91
        ///60
        ///67
        ///5
        ///8 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string student1 {
            get {
                return ResourceManager.GetString("student1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5
        ///17
        ///55
        ///9
        ///21
        ///74
        ///84
        ///26
        ///95
        ///19
        ///31
        ///4
        ///27
        ///39
        ///13
        ///23
        ///25
        ///47
        ///63
        ///41
        ///63
        ///39
        ///35
        ///71
        ///62
        ///21
        ///62
        ///68
        ///55
        ///59
        ///13
        ///50
        ///23
        ///86
        ///41
        ///93
        ///100
        ///20
        ///18
        ///92
        ///38
        ///58
        ///16
        ///27
        ///94
        ///53
        ///30
        ///9
        ///33
        ///35
        ///30
        ///29
        ///13
        ///11
        ///6
        ///43
        ///88
        ///70
        ///90
        ///44
        ///41
        ///44
        ///9
        ///7
        ///50
        ///1
        ///76
        ///34
        ///31
        ///80
        ///14
        ///35
        ///96
        ///91
        ///79
        ///12
        ///97
        ///92
        ///24
        ///68
        ///67
        ///89
        ///47
        ///20
        ///59
        ///32
        ///40
        ///66
        ///63
        ///26
        ///100
        ///57
        ///94
        ///86
        ///71
        ///41
        ///67
        ///12
        ///84
        ///26
        ///52
        ///75
        ///79
        ///93
        ///95
        ///69
        ///83
        ///50
        ///10
        ///2
        ///90
        ///7
        ///89
        ///64
        ///54
        ///54
        ///98
        ///45
        ///32
        ///70
        ///79
        ///11
        ///82
        ///69
        ///95
        ///87
        ///97
        ///1
        ///76
        ///54
        ///3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string student2 {
            get {
                return ResourceManager.GetString("student2", resourceCulture);
            }
        }
    }
}
